"""empty message

Revision ID: 0e9675582407
Revises: 
Create Date: 2020-02-10 17:56:49.338853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9675582407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows')
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'artist_image_link')
    op.drop_column('show', 'artist_name')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'past_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_image_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
